In [52]:
import numpy as np
import sympy

import torch

In [74]:
x = sympy.symbols('x')

poly = sympy.poly(-24 + 2*x + 17*x**2 - 8*x**3 + x**4)
poly

Poly(x**4 - 8*x**3 + 17*x**2 + 2*x - 24, x, domain='ZZ')

In [75]:
coeffs = torch.flip(torch.Tensor(poly.coeffs()), dims = (0, ))
coeffs

tensor([-24.,   2.,  17.,  -8.,   1.])

In [76]:
n = len(coeffs) - 1
C = torch.zeros((n, n))

for i in range(0, n-1):
    C[i, i+1] = 1
    
C[n-1, :] = -1 * coeffs[:-1]

In [77]:
for l in C:
    print(l)

tensor([0., 1., 0., 0.])
tensor([0., 0., 1., 0.])
tensor([0., 0., 0., 1.])
tensor([ 24.,  -2., -17.,   8.])


In [78]:
torch.linalg.eig(C)[0]

tensor([-1.0000+0.j,  4.0000+0.j,  3.0000+0.j,  2.0000+0.j])